In [ ]:
!pip install sklearn_som
!pip install sentence_transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 3.6 MB/s eta 0:00:00


In [ ]:
import pandas as pd


In [ ]:
data1 = pd.read_excel('sample1.xlsx')
data2 = pd.read_excel('sample2.xlsx')
data3 = pd.read_excel('sample3.xlsx')
data = pd.concat([data1,data2,data3])

In [ ]:
data = pd.read_excel('sample.xlsx')


In [ ]:
from sentence_transformers import SentenceTransformer
#danasone/bart-small-ru-en
# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-mpnet-base-v2")

# The sentences to encode
sentences = list(data['Заголовок'])

# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sentences)
print(embeddings.shape)
# [3, 384]

# 3. Calculate the embedding similarities
similarities = model.similarity(embeddings, embeddings,)
print(similarities)
# tensor([[1.0000, 0.6660, 0.1046],
#         [0.6660, 1.0000, 0.1411],
#         [0.1046, 0.1411, 1.0000]])


/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(4362, 768)
tensor([[1.0000, 0.5637, 0.5726,  ..., 0.8080, 0.5351, 0.5178],
        [0.5637, 1.0000, 0.5182,  ..., 0.6182, 0.5166, 0.7826],
        [0.5726, 0.5182, 1.0000,  ..., 0.5971, 0.5426, 0.4658],
        ...,
        [0.8080, 0.6182, 0.5971,  ..., 1.0000, 0.6138, 0.5979],
        [0.5351, 0.5166, 0.5426,  ..., 0.6138, 1.0000, 0.6123],
        [0.5178, 0.7826, 0.4658,  ..., 0.5979, 0.6123, 1.0000]])


In [ ]:
similarities.fill_diagonal_(0)

tensor([[0.0000, 0.5637, 0.5726,  ..., 0.8080, 0.5351, 0.5178],
        [0.5637, 0.0000, 0.5182,  ..., 0.6182, 0.5166, 0.7826],
        [0.5726, 0.5182, 0.0000,  ..., 0.5971, 0.5426, 0.4658],
        ...,
        [0.8080, 0.6182, 0.5971,  ..., 0.0000, 0.6138, 0.5979],
        [0.5351, 0.5166, 0.5426,  ..., 0.6138, 0.0000, 0.6123],
        [0.5178, 0.7826, 0.4658,  ..., 0.5979, 0.6123, 0.0000]])

In [ ]:
import torch
res = []
for i in range(data.shape[0]):
  am = torch.topk(torch.cat((similarities[i,:i],similarities[i, i+1:])), 5)
  res.append(am)

In [ ]:
import torch
res = []
for i in range(data.shape[0]):
  am = similarities[i].argmax()
  res.append(am)

In [ ]:
res[3]

tensor(231)

In [ ]:
similarities[3,231]

tensor(0.8970)

In [ ]:
print(data.iloc[231,0])
print(data.iloc[2,0])

Шорты женские
Колготки 4L


In [ ]:
data

Заголовок   Цена  Пониж.Цена  \
0                            Вещи пакетом женские 44 46    500           0   
1                          Эстонская вязаная шапка-шарф   1700           0   
2                                           Колготки 4L     80           0   
3                                          Черные шорты    150           0   
4                                  Ростовая кукла зайка  25000           0   
...                                                 ...    ...         ...   
4357     Женский мутоновый берет песочно-бежевого цвета   1995           0   
4358                              Женская меховая шапка      0           0   
4359                     Джинсовая куртка женская 42-44    500           0   
4360  Одежда для беременных(куртка, джинсы, лосины, ...    500           0   
4361             Норковая бежевая шапка-ушанка(обманка)    795           0   

      Просм. Всего  Просм. Сегодня Методы продвижения    Время поднятия  \
0              179               2                NaN  2022.01.30 10:54   
1              125               1                NaN  2022.01.30 01:13   
2              112               3                NaN  2022.01.30 11:20   
3               99               3                NaN  2022.01.29 20:00   
4               56              20                NaN  2022.01.29 17:17   
...            ...             ...                ...               ...   
4357           291               1                NaN  2021.12.31 21:16   
4358           763               1                NaN  2022.01.01 02:52   
4359            22               1                NaN  2021.12.31 14:23   
4360            44               1                NaN  2021.12.31 18:30   
4361           327               2                NaN  2021.12.31 21:16   

      Доставка                       ID продавца  Активных объявлений  ...  \
0            1  553c61295760195d3f29ecfde15f2ee0                  9.0  ...   
1            1  29005b39dc53f5e3305b74fd42a21b68                  5.0  ...   
2            0  a0d1476ab32a5f75d2673d5cd7d33deb                 10.0  ...   
3            1  751de2fe1ad4dc90acca66712a90a161                 11.0  ...   
4            1  a2f43224967b419229a4fa05305611e4                 23.0  ...   
...        ...                               ...                  ...  ...   
4357         1  49c3961af80152142f8794eadfbe49f3                  6.0  ...   
4358         0  ca6b33ab812c693bd0f7c0e945e7644d                 22.0  ...   
4359         1  4cbc6f283372b265312f08b81e464fce                  4.0  ...   
4360         0  481e91824930e4439f3bcf15199473a9                 16.0  ...   
4361         1  49c3961af80152142f8794eadfbe49f3                  6.0  ...   

                                                 Фото  \
0     https://21.img.avito.st/640x480/11970652021.jpg   
1     https://74.img.avito.st/640x480/11043409874.jpg   
2     https://73.img.avito.st/640x480/11970824573.jpg   
3     https://30.img.avito.st/640x480/11585050030.jpg   
4     https://85.img.avito.st/640x480/12738307985.jpg   
...                                               ...   
4357   https://49.img.avito.st/640x480/5055450849.jpg   
4358    https://54.img.avito.st/640x480/484904154.jpg   
4359  https://50.img.avito.st/640x480/11972240150.jpg   
4360  https://49.img.avito.st/640x480/11973952849.jpg   
4361   https://37.img.avito.st/640x480/5013671737.jpg   

                                          Unnamed: 13  \
0     https://68.img.avito.st/640x480/11970652068.jpg   
1     https://61.img.avito.st/640x480/11043410561.jpg   
2                                                 NaN   
3     https://89.img.avito.st/640x480/11585052289.jpg   
4     https://77.img.avito.st/640x480/12738307977.jpg   
...                                               ...   
4357   https://43.img.avito.st/640x480/5055451343.jpg   
4358    https://48.img.avito.st/640x480/484906648.jpg   
4359  https://27.img.avito.st/640x480/11972240027.jpg   
4360  https://38

In [ ]:
from sklearn_som.som import SOM # Кластеризация с использованием самоорганизующихся карт Кахонена
model1 = SOM(n = 25, m = 25, dim = embeddings.shape[1],max_iter = 300, random_state = 10)

labels1 = model1.fit_predict(embeddings)

In [ ]:
data['labels'] = labels1

In [ ]:
data.to_excel('res.xlsx')